"""Compute per-category statistics from the raw COCO instance annotations.

Run from the project root:

    python scripts/analyze_categories.py

Reads the candidate category pool from configs/dataset.yaml, measures
instance and image frequencies for every COCO category in the train and
val splits, prints the candidate table, and writes
reports/phase3_category_analysis.md. Exit code 0 on success.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = PROJECT_ROOT / "configs" / "dataset.yaml"
REPORT_PATH = PROJECT_ROOT / "reports" / "phase3_category_analysis.md"


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a YAML mapping")
    return data


def load_instances(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"annotation file not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    for key in ("images", "annotations", "categories"):
        if not isinstance(data.get(key), list):
            raise ValueError(f"{path.name}: '{key}' missing or not a list")
    return data


def measure(
    instances: dict[str, Any],
) -> tuple[dict[int, dict[str, Any]], int]:
    per_category: dict[int, dict[str, Any]] = {}
    for category in instances["categories"]:
        category_id = int(category["id"])
        per_category[category_id] = {
            "id": category_id,
            "name": str(category["name"]),
            "instances": 0,
            "instances_excl_crowd": 0,
            "image_ids": set(),
        }
    for annotation in instances["annotations"]:
        entry = per_category.get(int(annotation.get("category_id", -1)))
        if entry is None:
            continue
        entry["instances"] += 1
        if int(annotation.get("iscrowd", 0)) == 0:
            entry["instances_excl_crowd"] += 1
            image_id = annotation.get("image_id")
            if image_id is not None:
                entry["image_ids"].add(int(image_id))
    total_images = len(instances["images"])
    for entry in per_category.values():
        entry["images"] = len(entry.pop("image_ids"))
    return per_category, total_images


def build_rows(config: dict[str, Any], raw_dir: Path) -> list[dict[str, Any]]:
    selection = config.get("selection", {})
    candidates = [str(name) for name in selection.get("candidate_categories", [])]
    train = load_instances(raw_dir / config["source"]["train_annotations"])
    val = load_instances(raw_dir / config["source"]["val_annotations"])
    train_stats, train_images = measure(train)
    val_stats, val_images = measure(val)

    rows: list[dict[str, Any]] = []
    for category_id, entry in sorted(
        train_stats.items(), key=lambda item: item[1]["instances"], reverse=True
    ):
        val_entry = val_stats.get(category_id, {})
        rows.append(
            {
                "id": category_id,
                "name": entry["name"],
                "train_instances": entry["instances"],
                "train_instances_excl_crowd": entry["instances_excl_crowd"],
                "train_images": entry["images"],
                "val_instances": val_entry.get("instances", 0),
                "val_images": val_entry.get("images", 0),
                "image_pct": 100.0 * entry["images"] / train_images if train_images else 0.0,
                "candidate": entry["name"] in candidates,
            }
        )
    return rows


def render_report(
    rows: list[dict[str, Any]],
    config: dict[str, Any],
    train_images: int,
    val_images: int,
) -> str:
    selection = config.get("selection", {})
    min_instances = selection.get("min_instances_per_class")
    min_images = selection.get("min_images_per_class")
    candidate_rows = [row for row in rows if row["candidate"]]
    lines = [
        "# Phase 3 — COCO Category Analysis",
        "",
        "Generated by `python scripts/analyze_categories.py` from the raw",
        "COCO 2017 instance annotations (no statistics are hand-entered).",
        "",
        f"- Source images: train2017 = {train_images}, val2017 = {val_images}",
        f"- Candidate pool: {len(candidate_rows)} categories",
        f"- Selection guidance: >= {min_instances} train instances and"
        f" >= {min_images} train images (from configs/dataset.yaml)",
        "- `excl crowd` counts drop `iscrowd = 1` annotations, matching the",
        "  preparation rule (`include_iscrowd: false`).",
        "",
        "## Candidate categories (sorted by train instances)",
        "",
        "| Category | COCO id | Train instances | Train excl. crowd | Train images | % train images | Val instances | Val images |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in candidate_rows:
        lines.append(
            f"| {row['name']} | {row['id']} | {row['train_instances']:,} |"
            f" {row['train_instances_excl_crowd']:,} | {row['train_images']:,} |"
            f" {row['image_pct']:.1f}% | {row['val_instances']:,} |"
            f" {row['val_images']:,} |"
        )
    lines += [
        "",
        "## All COCO categories (context)",
        "",
        "| Category | COCO id | Train instances | Train images | Candidate |",
        "|---|---:|---:|---:|:---:|",
    ]
    for row in rows:
        flag = "yes" if row["candidate"] else "no"
        lines.append(
            f"| {row['name']} | {row['id']} | {row['train_instances']:,} |"
            f" {row['train_images']:,} | {flag} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="phase configuration (default: configs/dataset.yaml)",
    )
    args = parser.parse_args(argv)

    try:
        config = load_yaml(args.config)
        raw_dir = PROJECT_ROOT / config["source"]["raw_dir"]
        rows = build_rows(config, raw_dir)
        train = load_instances(raw_dir / config["source"]["train_annotations"])
        val = load_instances(raw_dir / config["source"]["val_annotations"])
    except (OSError, ValueError, json.JSONDecodeError, KeyError) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1

    candidate_rows = [row for row in rows if row["candidate"]]
    header = (
        f"{'category':<16}{'id':>5}{'train_inst':>12}{'train_img':>11}"
        f"{'img_pct':>9}{'val_inst':>10}"
    )
    print(header)
    print("-" * len(header))
    for row in candidate_rows:
        print(
            f"{row['name']:<16}{row['id']:>5}{row['train_instances']:>12,}"
            f"{row['train_images']:>11,}{row['image_pct']:>8.1f}%"
            f"{row['val_instances']:>10,}"
        )

    report = render_report(
        rows, config, len(train["images"]), len(val["images"])
    )
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"[ok] wrote {REPORT_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
